name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test



  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: build/ios/iphoneos

  deploy_to_app_center:
    name: Deploy to App Center
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-apk

      - name: Install App Center CLI
        run: npm install -g appcenter-cli

      - name: List Distribution Groups
        run: |
          appcenter distribute groups list \
            --app ${{ secrets.APPCENTER_OWNER_NAME }}/${{ secrets.APPCENTER_ANDROID_APP_NAME }} \
            --token ${{ secrets.APPCENTER_ANDROID_TOKEN }}

      - name: Deploy to App Center
        run: |
          appcenter distribute release \
            --app ${{ secrets.APPCENTER_OWNER_NAME }}/${{ secrets.APPCENTER_ANDROID_APP_NAME }} \
            --file app-release.apk \
            --group "Collaborators" \
            --token ${{ secrets.APPCENTER_ANDROID_TOKEN }} \
            --release-notes "New release from CI/CD"



